# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

language: generic
env:
  global:
    - IDE_VERSION=1.8.10
  matrix:
    - BOARD="esp8266:esp8266:huzzah:FlashSize=4M3M,CpuFrequency=80"
    - BOARD="esp8266:esp8266:thing"
    - BOARD="esp32:esp32:huzzah"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
      arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --install-boards esp8266:esp8266;
      arduino --pref "boardsmanager.additional.urls=" --save-prefs;
      arduino --install-library NTPClient;
      arduino --install-library NTPClient;
    fi
  - if [[ "$BOARD" =~ "esp32:esp32:" ]]; then
      arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" --install-boards esp32:esp32;
      arduino --pref "boardsmanager.additional.urls=" --save-prefs;
      arduino --install-library NTPClient;
    fi
    
  - findAndReplace() { sed -i'' -e"s|$1|$2|g" "$3"; }
  - buildExampleSketch() {
      EXAMPLE_SKETCH=$PWD/examples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.ino;

      arduino --verbose-build --verify --board $BOARD $EXAMPLE_SKETCH;
    }
install:
  - arduino --install-library "AzureIoTUtility"
  - arduino --install-library "AzureIoTSocket_WiFi"
  - arduino --install-library "AzureIoTProtocol_MQTT"
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch telemetry_sample.c
